<tsd:PluginWindowBase
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:StudArrayPlugin"
        xmlns:tsd="clr-namespace:Tekla.Structures.Dialog;assembly=Tekla.Structures.Dialog"
        xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog" x:Class="StudArrayPlugin.MainWindow"
        mc:Ignorable="d"
        Title="StudArrayPlugin" FontSize="16" MinHeight="650" MaxHeight="650" MinWidth="800" MaxWidth="800">
    <tsd:PluginWindowBase.DataContext>
        <local:MainWindowViewModel></local:MainWindowViewModel>
    </tsd:PluginWindowBase.DataContext>
    <Grid>
        <Grid.Resources>
            <Style TargetType="TextBox">
                <Setter Property="Height" Value="30"/>
                <Setter Property="VerticalContentAlignment" Value="Center"/>
                <Setter Property="VerticalAlignment" Value="Center"/>
            </Style>
            <Style TargetType="Label">
                <Setter Property="Height" Value="30"/>
                <Setter Property="VerticalContentAlignment" Value="Center"/>
                <Setter Property="VerticalAlignment" Value="Center"/>
            </Style>
            <Style TargetType="UIControls:WpfFilterCheckBox">
                <Setter Property="Height" Value="30"/>
                <Setter Property="VerticalContentAlignment" Value="Center"/>
            </Style>
            <Style TargetType="ComboBox">
                <Setter Property="VerticalAlignment" Value="Center"/>
                <Setter Property="VerticalAlignment" Value="Center"/>
                <Setter Property="Height" Value="20"/>
            </Style>
        </Grid.Resources>
        <Grid.RowDefinitions>
            <RowDefinition Height="50"/>
            <RowDefinition/>
            <RowDefinition Height="50"/>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition/>
            <ColumnDefinition/>
        </Grid.ColumnDefinitions>

        <UIControls:WpfSaveLoad Grid.ColumnSpan="2" HorizontalAlignment="Stretch" VerticalAlignment="Stretch"/>
        <UIControls:WpfOkApplyModifyGetOnOffCancel Grid.ColumnSpan="2" HorizontalAlignment="Stretch" Grid.Row="3" VerticalAlignment="Stretch" ApplyClicked="WpfOkApplyModifyGetOnOffCancel_ApplyClicked" CancelClicked="WpfOkApplyModifyGetOnOffCancel_CancelClicked" GetClicked="WpfOkApplyModifyGetOnOffCancel_GetClicked" ModifyClicked="WpfOkApplyModifyGetOnOffCancel_ModifyClicked" OkClicked="WpfOkApplyModifyGetOnOffCancel_OkClicked" OnOffClicked="WpfOkApplyModifyGetOnOffCancel_OnOffClicked"/>

        <Grid Grid.Column="0" Grid.Row="1">
            <StackPanel HorizontalAlignment="Left" Margin="10,0,0,0" >
                <Label Content="Параметры и атрибуты деталей" HorizontalAlignment="Center" FontWeight="Bold"/>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="Profile"/>
                    <Label Content="Профиль упоров" Width="205"/>
                    <TextBox Text="{Binding Profile}" Width="100"/>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="Material"/>
                    <Label Content="Материал упоров" Width="205"/>
                    <TextBox Text="{Binding Material}" Width="100"/>
                    <UIControls:WpfMaterialCatalog x:Name="MaterialCatalog" SelectClicked="MaterialCatalog_SelectClicked" SelectionDone="MaterialCatalog_SelectionDone" HorizontalAlignment="Center" VerticalAlignment="Center" />
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudClass"/>
                    <Label Content="Класс упоров" Width="205"/>
                    <TextBox Text="{Binding StudClass}"  Width="100"/>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudPrefix"/>
                    <Label Content="Префикс деталей" Width="205"/>
                    <TextBox Text="{Binding StudPrefix}"  Width="100"/>
                </StackPanel>
            </StackPanel>
        </Grid>

        <Grid Grid.Column="1" Grid.Row="1">
            <StackPanel HorizontalAlignment="Left" Margin="0,0,0,0" >
                <Label Content="Параметры массива" HorizontalAlignment="Center" FontWeight="Bold"/>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudHeight"/>
                    <Label Content="Высота упоров" Width="240"/>
                    <TextBox Text="{Binding StudHeight}" Width="100"/>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudCrossStep"/>
                    <Label Content="Шаг упоров поперек" Width="240"/>
                    <TextBox Text="{Binding StudCrossStep}" Width="100"/>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudAlongStep"/>
                    <Label Content="Шаг упоров вдоль" Width="240"/>
                    <TextBox Text="{Binding StudAlongStep}" Width="100"/>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudCrossNum"/>
                    <Label Content="Количество поперек (1 или 2)" Width="240"/>
                    <TextBox Text="{Binding StudCrossNum}" Width="100"/>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudAlongNum"/>
                    <Label Content="Количество вдоль" Width="240"/>
                    <TextBox Text="{Binding StudAlongNum}" Width="100"/>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudOffset"/>
                    <Label Content="Отступ от начала массива" Width="240"/>
                    <TextBox Text="{Binding StudOffset}" Width="100"/>
                </StackPanel>
                <Separator Height="10"/>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudLastNum"/>
                    <Label Content="Кол-во доп.рядов в конце" Width="240"/>
                    <TextBox Text="{Binding StudLastNum}" Width="100"/>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudLastStep"/>
                    <Label Content="Шаг упоров в доп.рядах" Width="240"/>
                    <TextBox Text="{Binding StudLastStep}" Width="100"/>
                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudCreateBlue"/>
                    <Label VerticalAlignment="Center" VerticalContentAlignment="Center"  Content="Создавать синий упор (0 или 1)" Width="240"/>
                    <TextBox Text="{Binding StudCreateBlue}" Width="100"/>

                </StackPanel>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudCreateGreen"/>
                    <Label VerticalAlignment="Center" VerticalContentAlignment="Center" Content="Создавать зеленый упор (0 или 1)" Width="240"/>
                    <TextBox Text="{Binding StudCreateGreen}" Width="100"/>
                </StackPanel>
                <Separator Height="10"/>
                <StackPanel Orientation="Horizontal">
                    <UIControls:WpfFilterCheckBox AttributeName="StudReverse"/>
                    <Label VerticalAlignment="Center" VerticalContentAlignment="Center" Content="Перевернуть упоры (0 или 1)" Width="240"/>
                    <TextBox Text="{Binding StudReverse}" Width="100"/>
                </StackPanel>
            </StackPanel>
        </Grid>

    </Grid>
</tsd:PluginWindowBase>
